### ISSUE TITLE
Empathy Map - Identification

### ISSUE THREAD

**Issue by aishaxsyed** [aishaxsyed/ISDM-Tut-7-Group-6#2]
Can be designed for:

- Relationship Manager (RM)
- Customer
- Employee at CMC
- Developer

**Comment by aishaxsyed** [comment]
**Empathy Map for Customer**

![Customer EM](https://user-images.githubusercontent.com/62279254/81886223-79af5200-95df-11ea-90de-ade42c5b2204.png)

**POV Statement:** I am a customer who is trying to get holiday package information in the most effective way, so that I can get the best deal and destination. However, I am having difficulty contacting CMC employees and navigating through holiday packages.

**Comment by NancyT0** [comment]
**Empathy Map for Relationship Manager**
![empathy map (1)](https://user-images.githubusercontent.com/62288158/81824370-bf84ff80-9578-11ea-97f8-21822899df12.jpg)

**POV Statement**: I am a relationship manager at a travel company who wants to maximise the sale of holiday packages. However, I am feeling overwhelmed because there is insufficient staff so I cannot utilise my time efficiently to effectively sell packages.

**Comment by soumyatejpal** [comment]
**Empathy Map for Employee**

![image](https://user-images.githubusercontent.com/62487854/82007534-d37e4d80-96ad-11ea-8c76-0caa460fcc62.png)

**POV Statement:** I am an employee who is trying to reach target sales by effectively selling holiday packages and providing customers with information. However, I am worried that I am having to speak with customers who require information on holiday packages which fall out of my area of expertise.

**Comment by aishaxsyed** [comment]
The Empathy Maps and POV statements are now completed
